project:
  type: website
  output-dir: docs
  
website:
  title: "Zeb_Antonioli_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: 
        href: 
      - icon: github
        href: https://github.com/ZebAntonioli/Zeb_Antonioli_Website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Zeb Antonioli"

format:
  html:
    theme: lux
    toc: true

editor: source

