---
title: "African Elephants"
  image: ./../img/_8500126
---

## Introduction

Loxodonta africanan is arguably one of the most charismatic mega fauna species alive. Elephants have always captivated me since I was young. From the sheer size to the complex social structures, they remind me that we are not the only intelligent species on this earth. In 2023 I went to both Botswana and Kenya. In Chobe National Park near Kasane Botswana, the elephant populations are more tolerant of humans when compared to those of South Africa and eastern Africa. The lack of hunting and human wildlife conflict has allowed for these individuals to be more relaxed around people. This is not to say they are tame as I found out when one of the other boats was charged and tusked by a rouge male. I was informed this one of only a handful of instances of elephants behaving aggressively in this region. My experiences thankfully were not of the terrifying kind. One moment I was unable to photograph was our boat drifting close to an island in the channel of the river. On this island there was a small herd feeding with the matriarch and her calf near the water. I cannot say for certain, but we came within only mere meters of the matriarch. Nothing can describe watching as she flared her ears out and her calf hid behind her. I still get giddy thinking about that moment. Kenya was slightly less magical; however, I cannot understate how incredible being able to create artwork of these animals is.
